version: "3"

services:
  redis:
    image: redis:7.2.2
    container_name: redis
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network
    command: redis-server --requirepass ${REDIS_PASSWORD}

networks:
  app-network:
    driver: bridge

volumes:
  redis-data:
